{{- $appName := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $fullname := printf "%s-%s" .Release.Name $appName | trunc 63 | trimSuffix "-" -}}
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" $fullname }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ default "10Gi" .Values.persistence.size }}
  storageClassName: {{ default "microk8s-hostpath" .Values.persistence.storageClassName }}

{{- end }}
