apiVersion: v1
kind: Service
metadata:
  name: {{ include "scipion3-remote.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: novnc
  selector:
    app.kubernetes.io/name: {{ include "scipion3-remote.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
