# Host configuration for Kubernetes cluster

[localhost]
NAME = Kubernetes
PARALLEL_COMMAND = /usr/local/bin/qsub
SUBMIT_COMMAND = /usr/local/bin/qsub %(JOB_SCRIPT)s
CANCEL_COMMAND = /usr/local/bin/qdel %(JOB_ID)s
CHECK_COMMAND = /usr/local/bin/qstat %(JOB_ID)s
SUBMIT_TEMPLATE = #!/bin/bash
    %(JOB_COMMAND)s
MANDATORY = True
QUEUES = {"default": []}
