# Scipion configuration

[PYWORKFLOW]
SCIPION_HOME = /opt/scipion
SCIPION_USER_DATA = /home/scipion/ScipionUserData
SCIPION_TESTS = /home/scipion/ScipionUserData/tests
SCIPION_NOTIFY = False
SCIPION_USE_QUEUE = True
