{{- $ctl := .Values.controller | default dict -}}
{{- if and (kindIs "map" $ctl) ($ctl.enabled | default false) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scipion-controller-config
  labels:
{{ include "scipion3-remote.labels" . | indent 4 }}
data:
  tools.yaml: |
{{ .Files.Get "config/tools.yaml" | indent 4 }}
{{- end }}
