{{- if .Values.vnc.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scipion3-remote.fullname" . }}-vnc
  labels:
{{ include "scipion3-remote.labels" . | indent 4 }}
type: Opaque
stringData:
  VNC_PASSWORD: {{ .Values.vnc.password | quote }}
{{- end }}
