apiVersion: v1
kind: Service
metadata:
  name: {{ include "scipion3-remote.fullname" . }}
  labels:
{{ include "scipion3-remote.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: novnc
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
{{ include "scipion3-remote.selectorLabels" . | indent 4 }}
