image:
  repository: localhost:32000/scipion3-remote  # TODO: Change to non-local registry
  tag: latest
  pullPolicy: IfNotPresent

gpu:
  enabled: true  # TODO: Add maybe selection of GPU if more present

resources:
  requests:
    cpu: "2"
    memory: "8Gi"  # NOTE: Needs to be > 4, otherwise crash
  limits:
    cpu: "4"
    memory: "16Gi"

vnc:
  display: 1
  geometry: "1920x1080"  # NOTE: Scipion does not work well with higher resolutions
  depth: 24
  passwordSecretName: "VNC_PASSWORD"  # TODO: Should work but does not...
  password: "test"  # TODO: Remove, should be resolved by line up but does not work

ingress:
  enabled: true
  className: public
  host: ""  # NOTE: Match any possible host, if needed specify per node
  tls:
    enabled: false  # TLS for internal network not needed
    secretName: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80

persistence:
  size: 10Gi  # TODO: Increase before deploy!
  accessMode: ReadWriteOnce
  storageClassName: microk8s-hostpath
  existingClaim: ""

nodeSelector: {}
tolerations: []
affinity: {}
