controller:
  enabled: true
  image:
    repository: cerit.io/scipion/container-controller
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 5000
    nodePort: 30080

  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "1",    memory: "512Mi" }

  storageMode: "pvc"
  projectsPVC: "scipion-scipion3-remote-data"
  localPath: "/projects"
  jobsTTL: 600
  jobsCleanupInterval: 120
  maxFinishedJobs: 3

  workerPullPolicy: "Always"

  onedata:
    enabled: false
    image: ""
    provider: ""
    space: ""
    tokenSecret: ""
    extraArgs: []

  nodeSelectorJson: {}
  tolerationsJson: {}

  # NodePort exposed by the GUI service for noVNC access.
  vncNodePort: 31335
